name: Publish Backend Docker image

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'infra/docker/**'
      - 'docker-compose.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: infra/docker/backend.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/backend:latest
        platforms: linux/amd64,linux/arm64