name: Publish Backend Docker Image
on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - "infra/docker/backend.Dockerfile"
      - ".github/workflows/docker-publish.yml"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/backend.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest
